# Generated by Django 3.0.3 on 2020-02-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_blog', '0002_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='key_words',
            field=models.ManyToManyField(to='my_blog.Keywords'),
        ),
    ]
